In [1]:
import pandas as pd
import re

In [2]:
df = pd.read_csv("internshala_multi_domain_jobs.csv")
df

,domain,job_title,company,location,stipend,start_date,duration,apply_by,job_link
0,Data Analyst,Data Analytics,Deep Life Savers,"Secunderabad, Hyderabad","₹ 60,000 /month",NaN,NaN,NaN,https://internshala.com/internship/detail/part...
1,Data Analyst,International Marketing Strategy,Abhishek Agrawal,Ahmedabad,"₹ 10,000 - 15,000 /month",NaN,NaN,NaN,https://internshala.com/internship/detail/part...
2,Data Analyst,Global Talent Intern,AIESEC India,Top international cities,Unpaid,NaN,NaN,NaN,https://internshala.com/internship/detail/glob...
3,Data Analyst,Data Analytics,VIZON,Work from home,"₹ 10,000 - 17,000 /month",NaN,NaN,NaN,https://internshala.com/internship/detail/work...
4,Data Analyst,Business Strategy,ConsultiFI Data Services,Ranchi,"₹ 5,000 - 25,000 /month",NaN,NaN,NaN,https://internshala.com/internship/detail/busi...
...,...,...,...,...,...,...,...,...,...
591,UI/UX Design,UI/UX Design – Motion & Interaction Design Focus,Fission Infotech,Hyderabad,"₹ 8,000 - 12,000 /month",NaN,NaN,NaN,https://internshala.com/internship/detail/ui-u...
592,UI/UX Design,UI/UX Design,Infits,Work from home,"₹ 5,500 - 7,000 /month",NaN,NaN,NaN,https://internshala.com/internship/detail/work...
593,UI/UX Design,Graphic Design,Eduminatti,Work from home,"₹ 5,000 - 10,000 /month",NaN,NaN,NaN,https://internshala.com/internship/detail/work...
594,UI/UX Design,Graphic Design,TransPacks Technologies,Noida,"₹ 10,000 - 16,000 /month",NaN,NaN,NaN,https://internshala.com/internship/detail/grap...
595,UI/UX Design,Graphic Design,Niwi,Noida,"₹ 8,000 - 10,000 /month",NaN,NaN,NaN,https://internshala.com/internship/detail/grap...

In [3]:
df = df.drop_duplicates()

In [4]:
df["job_title"] = df["job_title"].str.strip()
df["company"] = df["company"].str.strip()
df["domain"] = df["domain"].str.strip()

C:\Users\SAMIKSHA\AppData\Local\Temp\ipykernel_18256\3780863455.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["job_title"] = df["job_title"].str.strip()
C:\Users\SAMIKSHA\AppData\Local\Temp\ipykernel_18256\3780863455.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["company"] = df["company"].str.strip()
C:\Users\SAMIKSHA\AppData\Local\Temp\ipykernel_18256\3780863455.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["domain"] = df["domain"].str.strip()

In [6]:
df["location"] = df["location"].astype(str).str.strip()

df["location"] = df["location"].str.replace("Work from home", "Remote", case=False)

df["is_remote"] = df["location"].str.contains("Remote", case=False, na=False)

df["city"] = df["location"].apply(lambda x: "Remote" if "Remote" in x else x.split(",")[0])

C:\Users\SAMIKSHA\AppData\Local\Temp\ipykernel_18256\4130344478.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["location"] = df["location"].astype(str).str.strip()
C:\Users\SAMIKSHA\AppData\Local\Temp\ipykernel_18256\4130344478.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["location"] = df["location"].str.replace("Work from home", "Remote", case=False)
C:\Users\SAMIKSHA\AppData\Local\Temp\ipykernel_18256\4130344478.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["is_remote"] = df["location"].str.contains("Remote", case=False, na=False)
C:\Users\SAMIKSHA\AppData\Local\Temp\ipykernel_18256\4130344478.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["city"] = df["location"].apply(lambda x: "Remote" if "Remote" in x else x.split(",")[0])

In [20]:
def extract_avg_stipend(text):
    text = str(text)

    # Remove commas (VERY IMPORTANT)
    text = text.replace(",", "")

    # Extract full numbers
    numbers = re.findall(r'\d+', text)
    numbers = [int(n) for n in numbers]

    if len(numbers) >= 2:
        return sum(numbers[:2]) / 2
    elif len(numbers) == 1:
        return numbers[0]
    else:
        return None

df["stipend_clean"] = df["stipend"].apply(extract_avg_stipend)

In [21]:
def stipend_category(x):
    if pd.isna(x):
        return "Unpaid"
    elif x < 5000:
        return "Low"
    elif x < 15000:
        return "Medium"
    else:
        return "High"

df["stipend_category"] = df["stipend_clean"].apply(stipend_category)

In [9]:
def work_type(loc):
    if "Remote" in loc:
        return "Remote"
    elif "," in loc:
        return "Hybrid"
    else:
        return "On-site"

df["work_type"] = df["location"].apply(work_type)

C:\Users\SAMIKSHA\AppData\Local\Temp\ipykernel_18256\1895872226.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["work_type"] = df["location"].apply(work_type)

In [10]:
df = df.reset_index(drop=True)

In [11]:
df

,domain,job_title,company,location,stipend,start_date,duration,apply_by,job_link,is_remote,city,stipend_clean,stipend_category,work_type
0,Data Analyst,Data Analytics,Deep Life Savers,"Secunderabad, Hyderabad","₹ 60,000 /month",NaN,NaN,NaN,https://internshala.com/internship/detail/part...,False,Secunderabad,30.0,Low,Hybrid
1,Data Analyst,International Marketing Strategy,Abhishek Agrawal,Ahmedabad,"₹ 10,000 - 15,000 /month",NaN,NaN,NaN,https://internshala.com/internship/detail/part...,False,Ahmedabad,NaN,Unpaid,On-site
2,Data Analyst,Global Talent Intern,AIESEC India,Top international cities,Unpaid,NaN,NaN,NaN,https://internshala.com/internship/detail/glob...,False,Top international cities,NaN,Unpaid,On-site
3,Data Analyst,Data Analytics,VIZON,Remote,"₹ 10,000 - 17,000 /month",NaN,NaN,NaN,https://internshala.com/internship/detail/work...,True,Remote,NaN,Unpaid,Remote
4,Data Analyst,Business Strategy,ConsultiFI Data Services,Ranchi,"₹ 5,000 - 25,000 /month",NaN,NaN,NaN,https://internshala.com/internship/detail/busi...,False,Ranchi,NaN,Unpaid,On-site
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
557,UI/UX Design,UI/UX Design – Motion & Interaction Design Focus,Fission Infotech,Hyderabad,"₹ 8,000 - 12,000 /month",NaN,NaN,NaN,https://internshala.com/internship/detail/ui-u...,False,Hyderabad,NaN,Unpaid,On-site
558,UI/UX Design,UI/UX Design,Infits,Remote,"₹ 5,500 - 7,000 /month",NaN,NaN,NaN,https://internshala.com/internship/detail/work...,True,Remote,NaN,Unpaid,Remote
559,UI/UX Design,Graphic Design,Eduminatti,Remote,"₹ 5,000 - 10,000 /month",NaN,NaN,NaN,https://internshala.com/internship/detail/work...,True,Remote,NaN,Unpaid,Remote
560,UI/UX Design,Graphic Design,TransPacks Technologies,Noida,"₹ 10,000 - 16,000 /month",NaN,NaN,NaN,https://internshala.com/internship/detail/grap...,False,Noida,NaN,Unpaid,On-site
561,UI/UX Design,Graphic Design,Niwi,Noida,"₹ 8,000 - 10,000 /month",NaN,NaN,NaN,https://internshala.com/internship/detail/grap...,False,Noida,NaN,Unpaid,On-site

In [12]:
def stipend_category(x):
    if x == 0 or pd.isna(x):
        return "Unpaid"
    elif x < 5000:
        return "Low"
    elif x < 15000:
        return "Medium"
    else:
        return "High"

df["stipend_category"] = df["stipend_clean"].apply(stipend_category)

In [13]:
df

,domain,job_title,company,location,stipend,start_date,duration,apply_by,job_link,is_remote,city,stipend_clean,stipend_category,work_type
0,Data Analyst,Data Analytics,Deep Life Savers,"Secunderabad, Hyderabad","₹ 60,000 /month",NaN,NaN,NaN,https://internshala.com/internship/detail/part...,False,Secunderabad,30.0,Low,Hybrid
1,Data Analyst,International Marketing Strategy,Abhishek Agrawal,Ahmedabad,"₹ 10,000 - 15,000 /month",NaN,NaN,NaN,https://internshala.com/internship/detail/part...,False,Ahmedabad,NaN,Unpaid,On-site
2,Data Analyst,Global Talent Intern,AIESEC India,Top international cities,Unpaid,NaN,NaN,NaN,https://internshala.com/internship/detail/glob...,False,Top international cities,NaN,Unpaid,On-site
3,Data Analyst,Data Analytics,VIZON,Remote,"₹ 10,000 - 17,000 /month",NaN,NaN,NaN,https://internshala.com/internship/detail/work...,True,Remote,NaN,Unpaid,Remote
4,Data Analyst,Business Strategy,ConsultiFI Data Services,Ranchi,"₹ 5,000 - 25,000 /month",NaN,NaN,NaN,https://internshala.com/internship/detail/busi...,False,Ranchi,NaN,Unpaid,On-site
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
557,UI/UX Design,UI/UX Design – Motion & Interaction Design Focus,Fission Infotech,Hyderabad,"₹ 8,000 - 12,000 /month",NaN,NaN,NaN,https://internshala.com/internship/detail/ui-u...,False,Hyderabad,NaN,Unpaid,On-site
558,UI/UX Design,UI/UX Design,Infits,Remote,"₹ 5,500 - 7,000 /month",NaN,NaN,NaN,https://internshala.com/internship/detail/work...,True,Remote,NaN,Unpaid,Remote
559,UI/UX Design,Graphic Design,Eduminatti,Remote,"₹ 5,000 - 10,000 /month",NaN,NaN,NaN,https://internshala.com/internship/detail/work...,True,Remote,NaN,Unpaid,Remote
560,UI/UX Design,Graphic Design,TransPacks Technologies,Noida,"₹ 10,000 - 16,000 /month",NaN,NaN,NaN,https://internshala.com/internship/detail/grap...,False,Noida,NaN,Unpaid,On-site
561,UI/UX Design,Graphic Design,Niwi,Noida,"₹ 8,000 - 10,000 /month",NaN,NaN,NaN,https://internshala.com/internship/detail/grap...,False,Noida,NaN,Unpaid,On-site

In [14]:
company_counts = df["company"].value_counts()
df["company_openings"] = df["company"].map(company_counts)

In [16]:
df["domain_count"] = df["domain"].map(df["domain"].value_counts())

In [23]:
df

,domain,job_title,company,location,stipend,start_date,duration,apply_by,job_link,is_remote,city,stipend_clean,stipend_category,work_type,company_openings,domain_count
0,Data Analyst,Data Analytics,Deep Life Savers,"Secunderabad, Hyderabad","₹ 60,000 /month",NaN,NaN,NaN,https://internshala.com/internship/detail/part...,False,Secunderabad,60000.0,High,Hybrid,2,81
1,Data Analyst,International Marketing Strategy,Abhishek Agrawal,Ahmedabad,"₹ 10,000 - 15,000 /month",NaN,NaN,NaN,https://internshala.com/internship/detail/part...,False,Ahmedabad,12500.0,Medium,On-site,1,81
2,Data Analyst,Global Talent Intern,AIESEC India,Top international cities,Unpaid,NaN,NaN,NaN,https://internshala.com/internship/detail/glob...,False,Top international cities,NaN,Unpaid,On-site,1,81
3,Data Analyst,Data Analytics,VIZON,Remote,"₹ 10,000 - 17,000 /month",NaN,NaN,NaN,https://internshala.com/internship/detail/work...,True,Remote,13500.0,Medium,Remote,12,81
4,Data Analyst,Business Strategy,ConsultiFI Data Services,Ranchi,"₹ 5,000 - 25,000 /month",NaN,NaN,NaN,https://internshala.com/internship/detail/busi...,False,Ranchi,15000.0,High,On-site,1,81
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
557,UI/UX Design,UI/UX Design – Motion & Interaction Design Focus,Fission Infotech,Hyderabad,"₹ 8,000 - 12,000 /month",NaN,NaN,NaN,https://internshala.com/internship/detail/ui-u...,False,Hyderabad,10000.0,Medium,On-site,1,120
558,UI/UX Design,UI/UX Design,Infits,Remote,"₹ 5,500 - 7,000 /month",NaN,NaN,NaN,https://internshala.com/internship/detail/work...,True,Remote,6250.0,Medium,Remote,2,120
559,UI/UX Design,Graphic Design,Eduminatti,Remote,"₹ 5,000 - 10,000 /month",NaN,NaN,NaN,https://internshala.com/internship/detail/work...,True,Remote,7500.0,Medium,Remote,4,120
560,UI/UX Design,Graphic Design,TransPacks Technologies,Noida,"₹ 10,000 - 16,000 /month",NaN,NaN,NaN,https://internshala.com/internship/detail/grap...,False,Noida,13000.0,Medium,On-site,1,120
561,UI/UX Design,Graphic Design,Niwi,Noida,"₹ 8,000 - 10,000 /month",NaN,NaN,NaN,https://internshala.com/internship/detail/grap...,False,Noida,9000.0,Medium,On-site,1,120

In [24]:
df.to_csv("internshala_cleaned_jobs.csv", index=False)
print(df.head())

         domain                         job_title                   company  \
0  Data Analyst                    Data Analytics          Deep Life Savers
1  Data Analyst  International Marketing Strategy          Abhishek Agrawal
2  Data Analyst              Global Talent Intern              AIESEC India
3  Data Analyst                    Data Analytics                     VIZON
4  Data Analyst                 Business Strategy  ConsultiFI Data Services

                   location                   stipend  start_date  duration  \
0   Secunderabad, Hyderabad           ₹ 60,000 /month         NaN       NaN
1                 Ahmedabad  ₹ 10,000 - 15,000 /month         NaN       NaN
2  Top international cities                    Unpaid         NaN       NaN
3                    Remote  ₹ 10,000 - 17,000 /month         NaN       NaN
4                    Ranchi   ₹ 5,000 - 25,000 /month         NaN       NaN

   apply_by                                           job_link  is_remote  \
0       NaN  https://internshala.com/internship/detail/part...      False
1       NaN  https://internshala.com/internship/detail/part...      False
2       NaN  https://internshala.com/internship/detail/glob...      False
3       NaN  https://internshala.com/internship/detail/work...       True
4       NaN  https://internshala.com/internship/detail/busi...      False

                       city  stipend_clean stipend_category work_type  \
0              Secunderabad        60000.0             High    Hybrid
1                 Ahmedabad        12500.0           Medium   On-site
2  Top international cities            NaN           Unpaid   On-site
3                    Remote        13500.0           Medium    Remote
4                    Ranchi        15000.0             High   On-site

   company_openings  domain_count
0                 2            81
1                 1            81
2                 1            81
3                12            81
4                 1            81